background_opacity 0.7
dynamic_background_opacity yes
foreground #03adfc
# background #000000

allow_remote_control yes

font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

font_size 10.0
window_padding_width 0

include current-theme.conf
listen_on unix:@kitty
